Models/ErrorViewModel.cs
namespace Nomina.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using Nomina.Clases;
using Nomina.Models;
using NuGet.Packaging;
using System.Collections.Generic;
using System.Net;

namespace Nomina.Controllers
{
    public class EmpleadoController : Controller
    {
        //List<Empleado> ListaEmpleado;
        public  List<Empleado> ListaEmpleado = new List<Empleado>();

        public IActionResult Index()
        {
            // new List<Empleado
            ListaEmpleado.Add
                
                ( 

           
                new Empleado(){Id=12,Nombre="wally",apellido="Martínez",Edad=29,fecha_nacimientos="12/9/1994",sexo="Masculino",salario=80000,pais="RD",provincia="santo domnigo",municipio="santo domingo oeste",barrios="managuayabo",si_posee_licencia=true}
                //new Empleado(){Id=15,Nombre="Dios",apellido="cristo",Edad=35,fecha_nacimientos="11/2/1992",sexo="Masculino",salario=90000,pais="RD",provincia="santo Domingo",municipio="santo domingo oeste",barrios="mana guayabo",si_posee_licencia=true},
               // new Empleado(){Id=16,Nombre="pedro",apellido="pimente",Edad=55,fecha_nacimientos="13/4/1993",sexo="Masculino",salario=70000,pais="RD",provincia="santo domnigo",municipio="santo domingo oeste",barrios="bayona",si_posee_licencia=false}
                //new Empleado(){Id=18,Nombre="Joan",apellido="Rodriguez",Edad=45,fecha_nacimientos="16/9/1996",sexo="Masculino",salario=60000,pais="RD",provincia="santo domnigo",municipio="santo domingo este",barrios="la caoba",si_posee_licencia=false},
                //new //Empleado(){Id=19,Nombre="Kaisaris",apellido="Gaston",Edad=66,fecha_nacimientos="18/9/1997",sexo="femenina",salario=50000,pais="RD",provincia="santo domnigo",municipio="santo domingo este",barrios="san isidro",si_posee_licencia=true},
                //new Empleado(){Id=20,Nombre="ana",apellido="Gaston",Edad=28,fecha_nacimientos="19/9/1998",sexo="femenina",salario=30000,pais="RD",provincia="santo domnigo",municipio="santo domingo este",barrios="mameyes",si_posee_licencia=false}
               
           );

            ListaEmpleado.Add(new Empleado() { Id = 18, Nombre = "Joan", apellido = "Rodriguez", Edad = 45, fecha_nacimientos = "16/9/1996", sexo = "Masculino", salario = 60000, pais = "RD", provincia = "santo domnigo", municipio = "santo domingo este", barrios = "la caoba", si_posee_licencia = false });


          var  listaEmpleado = (from Empleado in ListaEmpleado
                             select Empleado).ToList();

            return View(listaEmpleado);
        }

        public IActionResult AgregarEmpleado()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AgregarEmpleado(Empleado oEmpleado)
        {
            if (!ModelState.IsValid)
            {
                return View (oEmpleado);
            }
            else
            {


                ListaEmpleado.Add(new ()
                {
                    Id = oEmpleado.Id,
                    Nombre = oEmpleado.Nombre,
                    apellido  = oEmpleado.apellido,
                    Edad = oEmpleado.Edad,
                    fecha_nacimientos  = oEmpleado.fecha_nacimientos,
                    sexo = oEmpleado.sexo,
                    salario = oEmpleado.salario,
                    pais = oEmpleado.pais,
                    provincia = oEmpleado.provincia,
                    municipio = oEmpleado.municipio,
                    barrios = oEmpleado.barrios,
                    si_posee_licencia = oEmpleado.si_posee_licencia


                });
                // return RedirectToAction("Index","Empleado") ;
                //     RedirectToAction("Index", "Empleado");

             //   var lista = ListaEmpleado;
                return RedirectToAction ("Index","Empleado");
                
            }
           
        }    

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Nomina.Models;
using System.Diagnostics;

namespace Nomina.Controllers
{
    public class HomeController : Controller
    {
       

        public HomeController(ILogger<HomeController> logger)
        {
            
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NominaController.cs
using Microsoft.AspNetCore.Mvc;
using Nomina.Clases;
using System.Collections.Generic;


namespace Nomina.Controllers
{
    public class NominaController : Controller
    {
        public IActionResult Index()
        {
            List<Nomina1> ListaNomina = new List<Nomina1>()
            {
                new Nomina1(){Sueldo_bruto=80000,Sueldo_neto=54328,Tss=5672 ,Isr=20000,Fecha_creación="12/4/2000",Fecha_nomina="Los dia 15 & 30"},
                new Nomina1(){Sueldo_bruto=90000,Sueldo_neto=65619,Tss=6381 ,Isr=18000,Fecha_creación="18/4/2001",Fecha_nomina="Los dia 15 & 30"},
                new Nomina1(){Sueldo_bruto=70000,Sueldo_neto=51037,Tss=4963 ,Isr=14000,Fecha_creación="17/4/2002",Fecha_nomina="Los dia 15 & 30"},
                new Nomina1(){Sueldo_bruto=60000,Sueldo_neto=43746,Tss=4254 ,Isr=12000,Fecha_creación="16/4/2003",Fecha_nomina="Los dia 15 & 30"},
                new Nomina1(){Sueldo_bruto=50000,Sueldo_neto=36455,Tss=3545 ,Isr=10000,Fecha_creación="14/4/2004",Fecha_nomina="Los dia 15 & 30"},
                new Nomina1(){Sueldo_bruto=40000,Sueldo_neto=54328,Tss=2836 ,Isr=8000,Fecha_creación="15/4/2005",Fecha_nomina="Los dia 15 & 30"}
            };

            ListaNomina = (from Nomina in ListaNomina
                           select Nomina).ToList();

            return View(ListaNomina);
        }

        public IActionResult Agregar()
        {


            return View();
        }

        [HttpPost]
        public IActionResult Agregar(Nomina1 onomina)
        {

            if (!ModelState.IsValid)
            {
                return View(onomina);
            }
            else
            {
                List<Nomina1> listaNomina = new List<Nomina1>();
                listaNomina.Add(onomina);
            }

            return RedirectToAction("Index");
        }
    }
}

Views/Empleado/AgregarEmpleado.cshtml
@using Nomina.Models;
@using Nomina.Controllers;
@using Nomina.Clases;
@model Empleado




@{
    ViewData["Title"] = "AgregarEmpleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>AgregarEmpleado</h1>
<hr />
<h3 class="text-center text-light bg-dark">Formulario</h3>
<form asp-controller="Empleado" asp-action="AgregarEmpleado" method="post">
<div class="row">
    <div class="col-md-6">
       
        
            <div>
                @Html.LabelFor(p=>p.Id)
                @Html.TextBoxFor(p=>p.Id, new {@class="form-control"})
               @*  @Html.ValidationMessageFor(p=>p.Id,null, new {@class="text-danger"}) *@
                
            </div>

            <div>
                @Html.LabelFor(p=>p.Nombre)
                @Html.TextBoxFor(p=>p.Nombre, new {@class="form-control"})
                @* @Html.ValidationMessageFor(p=>p.Nombre,null,new {@class="text-danger"}) *@

            </div>

            <div>
                @Html.LabelFor(p=>p.apellido)
                @Html.TextBoxFor(p=>p.apellido, new {@class="form-control"})

            </div>

             <div>
                @Html.LabelFor(p=>p.Edad)
                @Html.TextBoxFor(p=>p.Edad, new {@class="form-control"})

            </div>

            <div>
                @Html.LabelFor(p=>p.fecha_nacimientos)
                @Html.EditorFor(p=>p.fecha_nacimientos, new  {htmlAttributes = new {@class="form-control"} })

            </div>
            <div>
                @Html.LabelFor(p=>p.sexo)
                @Html.TextBoxFor(p=>p.sexo, new {@class="form-control"})

            </div>

            <div>
                @Html.LabelFor(p=>p.salario)
                @Html.TextBoxFor(p=>p.salario, new {@class="form-control"})

            </div>

            <div>
                @Html.LabelFor(p=>p.pais)
                @Html.TextBoxFor(p=>p.pais, new {@class="form-control"})

            </div>

             <div>
                @Html.LabelFor(p=>p.provincia)
                @Html.TextBoxFor(p=>p.provincia, new {@class="form-control"})

            </div>

            <div>
                @Html.LabelFor(p=>p.municipio)
                @Html.TextBoxFor(p=>p.municipio, new {@class="form-control"})

            </div>

            <div>
                @Html.LabelFor(p=>p.barrios)
                @Html.TextBoxFor(p=>p.barrios, new {@class="form-control"})

            </div>

            <div>
                @Html.LabelFor(p=>p.si_posee_licencia)
                @Html.TextBoxFor(p=>p.si_posee_licencia, new {@class="form-control"})

            </div>


            <br />
            <div style="margin:auto" >
            <input type="submit" class="btn btn-primary" value="Guarda" />
            </div>

            
        
    </div>
 </div>   
</form>

Views/Empleado/Index.cshtml
@using Nomina.Clases;
@model ICollection<Empleado>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Empleado</h1>
<br />
<div style="text-align:start;">
    @Html.ActionLink("Agregar","AgregarEmpleado","Empleado", null,new {@class="btn btn-primary"})
</div>
<table class="table table-primary"> 
    <thead class="tab-pane" >

        <tr class="table-dark">
            <th>Id</th>
            <th>Nombre</th>
            <th>apellido</th>
            <th>Edad</th>
            <th>Fecha_Nacimientos</th>
            <th>Sexo</th>
            <th>Salario</th>
            <th>pais</th>
            <th>Provicia</th>
            <th>Municipio</th>
            <th>Barrio</th>
            <th>Si_posse_licencia</th>
        </tr>
    </thead>

    <tbody>

        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Nombre</td>
                <td>@item.apellido</td>
                <td>@item.Edad</td>
                <td>@item.fecha_nacimientos</td>
                <td>@item.sexo</td>
                <td>@item.salario</td>
                <td>@item.pais</td>
                <td>@item.provincia</td>
                <td>@item.municipio</td>
                <td>@item.barrios</td>
                <td>@item.si_posee_licencia</td>
                <td>
                     <a class="btn btn-light"href="~Empleado/Editar/@item.Id">Editar</a>
                </td>
                <td>
                    <a class="btn btn-danger"href="~Empleado/Eliminar/@item.Id">Eliminar</a>
                </td>


            </tr>
        }
    </tbody>
</table>
    

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<h1 class="text-center text-warning ">Bienvenido a inicio</h1>

Views/Nomina/Agregar.cshtml
@using Nomina.Models;
@using Nomina.Controllers;
@using Nomina.Clases;
@model Nomina1

@{
    ViewData["Title"] = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Agregar Nomina</h1>
<hr />
<h3 class="text-center text-light bg-dark" >Formulario</h3>
<form asp-controller="Nomina" asp-action="Agregar" method="post">
    <div class="row">
    <div class="col-md-6">
       
        
            <div>
                @Html.LabelFor(p=>p.Sueldo_bruto)
                @Html.TextBoxFor(p=>p.Sueldo_bruto,new {@class="form-control"})
                @Html.ValidationMessageFor(p=>p.Sueldo_bruto, null ,new {@class="text-danger"})

            </div>

            <div>
                @Html.LabelFor(p=>p.Sueldo_neto)
                @Html.TextBoxFor(p=>p.Sueldo_neto,new {@class="form-control"})
                @Html.ValidationMessageFor(p=>p.Sueldo_neto,null,new{@class="danger"})
            </div>

            <div>
                @Html.LabelFor(p=>p.Tss)
                @Html.TextBoxFor(p=>p.Tss,new {@class="form-control"})
                @Html.ValidationMessageFor(p=>p.Tss,null,new{@class="danger"})
            </div>
            <div>
                @Html.LabelFor(p=>p.Isr)
                @Html.TextBoxFor(p=>p.Isr,new {@class="form-control"})
                @Html.ValidationMessageFor(p=>p.Isr,null,new{@class="danger"})
            </div>

            <div>
            
                    @Html.LabelFor(p=>p.Fecha_creación)
                    @Html.EditorFor(p=>p.Fecha_creación, new  {htmlAttributes = new {@class="form-control"} })
            </div>
            <div>
                    @Html.LabelFor(p=>p.Fecha_nomina)
                    @Html.EditorFor(p=>p.Fecha_nomina, new  {htmlAttributes = new {@class="form-control"} })
            </div>
            <br />
            <div style="margin:auto">
                <input type="submit" class="btn btn-primary" value="Guarda" />
            </div>

            
        
    </div>
</div>

</form>

Views/Nomina/Index.cshtml
@using Nomina.Clases;
@model ICollection<Nomina1>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1  >Nomina</h1>
<hr />
@* <button class="mb-2 btn btn-primary" >Agregar</button>
<a  class="mb-2 btn btn-success"   asp-action="Agregar" asp-controller="Nomina" >Formulario</a> *@

@Html.ActionLink("Agregar","Agregar","Nomina", null,new {@class="btn btn-primary"})

<table class=" table  table-info">
    <thead class=" table   table-active">

        <tr>
            <th>Sueldo Bruto</th>
            <th>Sueldo Neto</th>
            <th>TSS</th>
            <th>ISR</th>
            <th>Fecha_Creacion</th>
            <th>Fecha_Nomina</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Sueldo_bruto</td>
                <td>@item.Sueldo_neto</td>
                <td>@item.Tss</td>
                <td>@item.Isr</td>
                <td>@item.Fecha_creación</td>
                <td>@item.Fecha_nomina</td>

                <td>
                    <a class="btn btn-light" href="~Nomina1/Editar/@item.Sueldo_bruto">Editar</a>
                    <a class="btn btn-danger" href="~Nomina1/Eliminar/@item.Sueldo_bruto">Eliminar</a>
                </td>

            </tr>
            

           
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nomina</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Nomina.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nomina</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="Index">Empleado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nomina" asp-action="Index">Nomina</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Nomina - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>